version: '4'
services:
    postgresql:
        image: postgres:18.2
        container_name: product-postgres
        ports:
          - "5433:5432"
        environment:
          POSTGRES_USER: product_user
          POSTGRES_PASSWORD: product_pass
          POSTGRES_DB: product_service
        volumes:
          - ./data/postgres:/var/lib/postgresql/data

